name: Build and Publish Docker Image

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Determine OpenFHE version
      id: openfhe-version
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "version=main" >> $GITHUB_OUTPUT
          echo "ref=main" >> $GITHUB_OUTPUT
        elif [[ "${{ github.ref }}" == refs/tags/v* ]]; then
          # Extract version from tag (e.g., v1.0.0 -> 1.0.0)
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "ref=v$VERSION" >> $GITHUB_OUTPUT
        else
          # For other branches, use branch name as version
          BRANCH=${GITHUB_REF#refs/heads/}
          echo "version=$BRANCH" >> $GITHUB_OUTPUT
          echo "ref=$BRANCH" >> $GITHUB_OUTPUT
        fi

    - name: Log in to Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha,prefix={{branch}}-
        labels: |
          org.opencontainers.image.title=OpenFHE Buildbox
          org.opencontainers.image.description=Docker base image with pre-built OpenFHE libraries
          org.opencontainers.image.vendor=Matias Insaurralde
          org.opencontainers.image.source={{repo}}
          org.opencontainers.image.version={{version}}
          org.opencontainers.image.revision={{sha}}
          openfhe.version=${{ steps.openfhe-version.outputs.version }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: |
          type=gha
          type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache
        cache-to: |
          type=gha,mode=max
          type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache,mode=max
        build-args: |
          OPENFHE_VERSION=${{ steps.openfhe-version.outputs.version }}
          OPENFHE_REF=${{ steps.openfhe-version.outputs.ref }} 